/**
 * BLE Revshare Contract Types and Utilities
 *
 * Type definitions and utility functions for the BLE Revenue Sharing Arcium contract.
 * Supports Arcium MXE encrypted computation and durable nonce transactions.
 *
 * @see https://github.com/anon0mesh/contract
 */

import * as anchor from "@coral-xyz/anchor";
import { PublicKey } from "@solana/web3.js";

// ============================================
// PROGRAM IDS
// ============================================

/**
 * BLE Revshare Program ID (default localnet)
 * Update this with your deployed program ID
 */
export const BLE_REVSHARE_PROGRAM_ID = new PublicKey(
  "7fvHNYVuZP6EYt68GLUa4kU8f8dCBSaGafL9aDhhtMZN",
);

/**
 * Arcium Program ID
 */
export const ARCIUM_PROGRAM_ID = new PublicKey(
  "Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ",
);

// ============================================
// ACCOUNT TYPES
// ============================================

/**
 * Whitelist Entry Account
 * Stores information about whitelisted tokens
 */
export interface WhitelistEntry {
  mint: PublicKey;
  bump: number;
}

/**
 * Payment Event
 * Emitted when a payment is executed
 */
export interface PaymentEvent {
  payer: PublicKey;
  recipient: PublicKey;
  broadcaster: PublicKey | null;
  amount: number;
  timestamp: number;
}

/**
 * Payment Stats Output (from Arcium computation)
 * Encrypted statistics about payments
 */
export interface PaymentStatsOutput {
  totalPayments: number;
  totalVolume: number;
}

// ============================================
// INSTRUCTION PARAMETERS
// ============================================

/**
 * Parameters for execute_payment instruction
 */
export interface ExecutePaymentInstructionParams {
  /** Computation offset for Arcium (8 bytes) */
  computationOffset: anchor.BN;
  /** Amount to transfer (8 bytes) */
  amount: anchor.BN;
  /** Nonce for computation uniqueness (16 bytes / 128 bits) */
  nonce: bigint;
  /** X25519 public key for encryption (32 bytes) */
  pubKey: Uint8Array;
}

/**
 * Parameters for init_whitelist_token instruction
 */
export interface InitWhitelistTokenParams {
  mint: PublicKey;
}

/**
 * Parameters for remove_whitelist_token instruction
 */
export interface RemoveWhitelistTokenParams {
  mint: PublicKey;
}

// ============================================
// REVENUE SHARING CONFIGURATION
// ============================================

/**
 * Revenue sharing split ratios
 */
export const REVENUE_SHARE = {
  /** Recipient share (70%) */
  RECIPIENT_PERCENTAGE: 70,
  /** Broadcaster share (30%) */
  BROADCASTER_PERCENTAGE: 30,
} as const;

/**
 * Calculate revenue split amounts
 */
export function calculateRevenueSplit(totalAmount: number): {
  recipientAmount: number;
  broadcasterAmount: number;
} {
  const broadcasterAmount = Math.floor(
    (totalAmount * REVENUE_SHARE.BROADCASTER_PERCENTAGE) / 100,
  );
  const recipientAmount = totalAmount - broadcasterAmount;

  return {
    recipientAmount,
    broadcasterAmount,
  };
}

// ============================================
// PDA HELPERS
// ============================================

/**
 * Derive whitelist entry PDA
 */
export function deriveWhitelistEntryPDA(
  mint: PublicKey,
  programId: PublicKey = BLE_REVSHARE_PROGRAM_ID,
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("whitelist"), mint.toBuffer()],
    programId,
  );
}

/**
 * Derive Arcium signer PDA
 * This is the PDA used by Arcium for signing on behalf of the program
 */
export function deriveArciumSignerPDA(
  programId: PublicKey = BLE_REVSHARE_PROGRAM_ID,
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from("ArciumSignerAccount")],
    programId,
  );
}

// ============================================
// INSTRUCTION DISCRIMINATORS
// ============================================

/**
 * Instruction discriminators (8 bytes)
 * These should match the discriminators generated by Anchor
 */
export const INSTRUCTION_DISCRIMINATORS = {
  /** init_payment_stats_comp_def */
  INIT_COMP_DEF: Buffer.from([0, 0, 0, 0, 0, 0, 0, 0]),
  /** init_whitelist_token */
  INIT_WHITELIST: Buffer.from([1, 0, 0, 0, 0, 0, 0, 0]),
  /** remove_whitelist_token */
  REMOVE_WHITELIST: Buffer.from([2, 0, 0, 0, 0, 0, 0, 0]),
  /** execute_payment */
  EXECUTE_PAYMENT: Buffer.from([3, 0, 0, 0, 0, 0, 0, 0]),
  /** payment_stats_callback */
  PAYMENT_STATS_CALLBACK: Buffer.from([4, 0, 0, 0, 0, 0, 0, 0]),
} as const;

// ============================================
// SERIALIZATION HELPERS
// ============================================

/**
 * Serialize execute_payment instruction data
 */
export function serializeExecutePaymentData(
  params: ExecutePaymentInstructionParams,
): Buffer {
  // Total size: 8 (discriminator) + 8 (offset) + 8 (amount) + 16 (nonce) + 32 (pubKey) = 72 bytes
  const data = Buffer.alloc(72);

  // Discriminator (8 bytes)
  data.set(INSTRUCTION_DISCRIMINATORS.EXECUTE_PAYMENT, 0);

  // Computation offset (8 bytes)
  data.writeBigUInt64LE(BigInt(params.computationOffset.toString()), 8);

  // Amount (8 bytes)
  data.writeBigUInt64LE(BigInt(params.amount.toString()), 16);

  // Nonce (16 bytes / 128 bits)
  const nonceBuffer = Buffer.alloc(16);
  nonceBuffer.writeBigUInt64LE(params.nonce & BigInt("0xFFFFFFFFFFFFFFFF"), 0);
  nonceBuffer.writeBigUInt64LE(params.nonce >> BigInt(64), 8);
  data.set(nonceBuffer, 24);

  // X25519 pub_key (32 bytes)
  data.set(params.pubKey, 40);

  return data;
}

/**
 * Deserialize payment event data
 */
export function deserializePaymentEvent(data: Buffer): PaymentEvent {
  // Event structure:
  // - payer: PublicKey (32 bytes)
  // - recipient: PublicKey (32 bytes)
  // - broadcaster: Option<PublicKey> (1 + 32 bytes)
  // - amount: u64 (8 bytes)
  // - timestamp: i64 (8 bytes)

  let offset = 8; // Skip discriminator

  const payer = new PublicKey(data.subarray(offset, offset + 32));
  offset += 32;

  const recipient = new PublicKey(data.subarray(offset, offset + 32));
  offset += 32;

  // Option<PublicKey> for broadcaster
  const hasBroadcaster = data[offset] === 1;
  offset += 1;
  let broadcaster: PublicKey | null = null;
  if (hasBroadcaster) {
    broadcaster = new PublicKey(data.subarray(offset, offset + 32));
    offset += 32;
  }

  const amount = Number(data.readBigUInt64LE(offset));
  offset += 8;

  const timestamp = Number(data.readBigInt64LE(offset));

  return {
    payer,
    recipient,
    broadcaster,
    amount,
    timestamp,
  };
}

// ============================================
// VALIDATION HELPERS
// ============================================

/**
 * Validate X25519 public key
 */
export function validateX25519PubKey(pubKey: Uint8Array): boolean {
  return pubKey.length === 32;
}

/**
 * Validate nonce (must be 128 bits)
 */
export function validateNonce(nonce: bigint): boolean {
  return (
    nonce >= BigInt(0) &&
    nonce < BigInt("340282366920938463463374607431768211456")
  );
}

/**
 * Validate computation offset
 */
export function validateComputationOffset(offset: anchor.BN): boolean {
  return offset.gte(new anchor.BN(0));
}

// ============================================
// ARCIUM HELPERS
// ============================================

/**
 * Computation definition name for payment stats
 */
export const COMP_DEF_NAME = "payment_stats";

/**
 * Circuit hash for payment_stats
 * This should match the hash in the contract
 */
export const PAYMENT_STATS_CIRCUIT_HASH = "payment_stats"; // Placeholder

/**
 * Get Arcium environment configuration
 */
export interface ArciumEnvironment {
  arciumClusterOffset: number;
  arciumProgramId: PublicKey;
}

/**
 * Default Arcium configuration for devnet
 */
export const DEFAULT_ARCIUM_ENV: ArciumEnvironment = {
  arciumClusterOffset: 456, // Update based on your deployment
  arciumProgramId: ARCIUM_PROGRAM_ID,
};

// ============================================
// ERROR CODES
// ============================================

/**
 * BLE Revshare contract error codes
 */
export enum BleRevshareErrorCode {
  /** The broadcaster signature is required when providing a broadcaster account */
  BroadcasterSignatureRequired = 6000,
  /** Broadcaster token account is missing but broadcaster is present */
  MissingBroadcasterAccount = 6001,
  /** The computation was aborted */
  AbortedComputation = 6002,
  /** The cluster is not set */
  ClusterNotSet = 6003,
}

/**
 * Get error message for error code
 */
export function getErrorMessage(errorCode: BleRevshareErrorCode): string {
  switch (errorCode) {
    case BleRevshareErrorCode.BroadcasterSignatureRequired:
      return "The broadcaster signature is required when providing a broadcaster account";
    case BleRevshareErrorCode.MissingBroadcasterAccount:
      return "Broadcaster token account is missing but broadcaster is present";
    case BleRevshareErrorCode.AbortedComputation:
      return "The computation was aborted";
    case BleRevshareErrorCode.ClusterNotSet:
      return "The cluster is not set";
    default:
      return "Unknown error";
  }
}

// ============================================
// LOGGING HELPERS
// ============================================

/**
 * Log payment execution details
 */
export function logPaymentExecution(params: {
  amount: number;
  recipient: PublicKey;
  broadcaster?: PublicKey;
  mint: PublicKey;
  computationOffset: anchor.BN;
}) {
  console.log("=== BLE Revshare Payment Execution ===");
  console.log("Amount:", params.amount);
  console.log("Recipient:", params.recipient.toBase58());
  console.log("Broadcaster:", params.broadcaster?.toBase58() || "none");
  console.log("Mint:", params.mint.toBase58());
  console.log("Computation Offset:", params.computationOffset.toString());

  if (params.broadcaster) {
    const { recipientAmount, broadcasterAmount } = calculateRevenueSplit(
      params.amount,
    );
    console.log("Split:");
    console.log(`  - Recipient: ${recipientAmount} (70%)`);
    console.log(`  - Broadcaster: ${broadcasterAmount} (30%)`);
  }

  console.log("======================================");
}

/**
 * Log Arcium accounts
 */
export function logArciumAccounts(accounts: {
  computationAccount: PublicKey;
  clusterAccount: PublicKey;
  mxeAccount: PublicKey;
  mempoolAccount: PublicKey;
  executingPool: PublicKey;
  compDefAccount: PublicKey;
  poolAccount: PublicKey;
  clockAccount: PublicKey;
}) {
  console.log("=== Arcium Accounts ===");
  console.log("Computation:", accounts.computationAccount.toBase58());
  console.log("Cluster:", accounts.clusterAccount.toBase58());
  console.log("MXE:", accounts.mxeAccount.toBase58());
  console.log("Mempool:", accounts.mempoolAccount.toBase58());
  console.log("Executing Pool:", accounts.executingPool.toBase58());
  console.log("Comp Def:", accounts.compDefAccount.toBase58());
  console.log("Fee Pool:", accounts.poolAccount.toBase58());
  console.log("Clock:", accounts.clockAccount.toBase58());
  console.log("======================");
}

// ============================================
// TRANSACTION HELPERS
// ============================================

/**
 * Estimate transaction size for payment
 */
export function estimatePaymentTransactionSize(
  hasBroadcaster: boolean,
  hasMemo: boolean,
): number {
  // Base transaction size
  let size = 300; // Approximate base size

  // Payment instruction
  size += 1500; // Approximate instruction size with all accounts

  // Broadcaster adds extra accounts
  if (hasBroadcaster) {
    size += 100; // Additional signature and token account
  }

  // Memo adds extra instruction
  if (hasMemo) {
    size += 100; // Memo instruction
  }

  return size;
}

/**
 * Check if transaction is too large
 */
export function isTransactionTooLarge(size: number): boolean {
  // Solana transaction size limit is 1232 bytes
  return size > 1232;
}

// ============================================
// EXPORTS
// ============================================

export {
  ARCIUM_PROGRAM_ID as DEFAULT_ARCIUM_PROGRAM_ID,
  BLE_REVSHARE_PROGRAM_ID as DEFAULT_PROGRAM_ID
};

